name: motion
channels:
  - defaults
dependencies:
  - aom=3.12.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.5
  - fontconfig=2.15.0
  - fonttools=4.62.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=73.1
  - jpeg=9f
  - lcms2=2.17
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.3.0
  - libcxx=21.1.8
  - libdeflate=1.22
  - libexpat=2.7.5
  - libffi=3.4.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libopenblas=0.3.31
  - libopenjpeg=2.5.4
  - libpng=1.6.56
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - ncurses=6.5
  - openssl=3.5.5
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.12.13
  - python-dateutil=2.9.0post0
  - readline=8.3
  - setuptools=80.10.2
  - six=1.17.0
  - sqlite=3.51.2
  - tk=8.6.15
  - tornado=6.5.5
  - tzdata=2026a
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.2
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.5
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.13.0
      - attrs==26.1.0
      - av==17.0.0
      - blinker==1.9.0
      - certifi==2026.2.25
      - charset-normalizer==3.4.7
      - click==8.3.2
      - cloudpickle==3.1.2
      - cmake==4.3.1
      - datasets==3.6.0
      - deepdiff==8.6.2
      - diffusers==0.37.1
      - dill==0.3.8
      - docstring-parser==0.17.0
      - draccus==0.10.0
      - einops==0.8.2
      - etils==1.14.0
      - farama-notifications==0.0.4
      - filelock==3.25.2
      - flask==3.1.3
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - gymnasium==0.29.1
      - h11==0.16.0
      - hf-xet==1.4.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.9.1
      - idna==3.11
      - imageio==2.37.3
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==9.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonlines==4.0.0
      - kiwisolver==1.5.0
      - lerobot==0.3.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mujoco==3.6.0
      - multidict==6.7.1
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - numpy==2.4.4
      - opencv-python-headless==4.13.0.92
      - orderly-set==5.5.0
      - pandas==3.0.2
      - platformdirs==4.9.4
      - propcache==0.4.1
      - protobuf==6.33.6
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.20.0
      - pynput==1.8.1
      - pyobjc-core==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-quartz==12.1
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - pyserial==3.5
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - regex==2026.4.4
      - requests==2.33.1
      - rerun-sdk==0.22.1
      - rich==14.3.3
      - safetensors==0.7.0
      - scipy==1.17.1
      - sentry-sdk==2.57.0
      - shellingham==1.5.4
      - smmap==5.0.3
      - sympy==1.14.0
      - termcolor==3.3.0
      - toml==0.10.2
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tqdm==4.67.3
      - typeguard==4.5.1
      - typer==0.24.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tyro==1.0.12
      - urllib3==2.6.3
      - wandb==0.25.1
      - werkzeug==3.1.8
      - xxhash==3.6.0
      - yarl==1.23.0
      - zipp==3.23.0
      - zmq==0.0.0
